### ISSUE TITLE
Unable to pull the image

### ISSUE THREAD

**Issue by yananet** [linuxserver/docker-prowlarr#19]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Unable to pull the image
------------------------------

## Expected Behavior

The image file should be downloaded with `docker pull` command.

## Current Behavior

```
$ docker-compose pull
[+] Running 0/1
 ⠿ prowlarr Error                                                                                                  1.6s
Error response from daemon: manifest unknown
$
```
## Steps to Reproduce

1. create `docker-compose.yml` as described in `README.md`
2. run `docker-compose pull`
3. verify that the error was generated.
4.

## Environment
**OS:** : Arch linux
**CPU architecture:**   x86_64 and arm64
**How docker service was installed:** `pacman -S docker`

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
```
## Docker logs

```
$ docker-compose pull
[+] Running 0/1
 ⠿ prowlarr Error                                                                                                  1.6s
Error response from daemon: manifest unknown
$
```

## See Also
https://www.reddit.com/r/docker/comments/soszc0/unable_to_pull_prowlarr_using_dockercompose_on/

## Workaround
It worked if `develop` tag was added.
```
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
```
