### ISSUE TITLE
[BUG] Renovate bot suggests update to version 1.8.1259 from one year ago, latest currently is 1.2.2

### ISSUE THREAD

**Issue by floryn08** [linuxserver/docker-prowlarr#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Renovate bot suggests updating to version 1.8.1259 from one year ago, the latest currently is 1.2.2. Blocking this merge request by renovate prevents updating further.

### Expected Behavior

The 1.8.1259 tag should be removed from the container registry to avoid being picked up as a newer version.

### Steps To Reproduce

1. have a docker-compose file with prowlarr
```
 prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.2.2
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/media-management/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media-management-network
  ```
2. configure renovate bot for repository
3. renovate bot creates merge request for update to 1.8.1259 which is an incorrect tag from one year ago

### Environment

```markdown
n/a
```

### CPU architecture

arm64

### Docker creation

```bash
n/a
```

### Container logs

```bash
n/a
```

Link to tag: https://hub.docker.com/layers/linuxserver/prowlarr/1.8.1259/images/sha256-9af25e5a3d9ffae44726ecf4d1e2db21b3c389ff8c2d242e295988b7f3d14a49?context=explore
